[versions]
# Kotlin
kotlin-version = "1.9.23" # https://github.com/JetBrains/kotlin
kotlin-coroutines = "1.8.1" # https://github.com/Kotlin/kotlinx.coroutines
kotlin-json = "1.7.1" # https://github.com/Kotlin/kotlinx.serialization
kotlin-kaml = "0.60.0" # https://github.com/charleskorn/kaml

# Drivers
driver-jdbc = "3.46.0.0"
driver-mysql = "8.0.33"

# Minecraft
minecraft-version = "1.19.2"
minecraft-velocity = "3.1.1"
minecraft-spigot = "1.21-R0.1-SNAPSHOT"
minecraft-papi = "2.11.6"
minecraft-protocollib = "5.1.0"
minecraft-wg = "7.0.7"
minecraft-vault = "1.7.1"
minecraft-coreprotect = "21.2"
minecraft-astralibs = "2.28.0"
minecraft-bstats = "3.0.2"
minecraft-mockbukkit = "3.93.0"

# Testing
tests-org-testing = "7.1.0"
tests-junit = "4.12"
tests-mockito = "4.0.0"
tests-junit-jupiter-api = "5.9.1"
tests-junit-bom = "5.7.0"

# Fabric
minecraft-fabric-loom = "1.7.2"
minecraft-fabric-kotlin = "1.11.0+"
minecraft-fabric-loader = "0.15.11"
minecraft-fabric-api = "0.100.6+"

# Forge
minecraft-forge-net = "6.0.25"
minecrft-forge-version = "1.19.2-43.1.52"

# klibs
klibs-gradleplugin = "1.3.4" # https://github.com/makeevrserg/gradle-plugin

# Shadow
gradle-shadow = "8.0.0"

# BuildConfig
gradle-buildconfig = "5.3.5"

# Exposed
exposed = "0.52.0"

[libraries]
# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-coreJvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-version" }
kotlin-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-json" }
kotlin-serializationKaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kotlin-kaml" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }

# Shadow
gradle-shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "gradle-shadow" }

# Drivers
driver-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "driver-jdbc" }
driver-mysql = { module = "mysql:mysql-connector-java", version.ref = "driver-mysql" }

# Testing
tests-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

# Exposed
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }

# Minecraft
minecraft-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "minecraft-spigot" }
minecraft-spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "minecraft-spigot" }
minecraft-spigot-core = { module = "org.spigotmc:spigot", version.ref = "minecraft-spigot" }
minecraft-velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "minecraft-velocity" }
minecraft-protocollib = { module = "com.comphenix.protocol:ProtocolLib", version.ref = "minecraft-protocollib" }
minecraft-papi = { module = "me.clip:placeholderapi", version.ref = "minecraft-papi" }
minecraft-vaultapi = { module = "com.github.MilkBowl:VaultAPI", version.ref = "minecraft-vault" }
minecraft-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "minecraft-bstats" }
minecraft-mockbukkit = { module = "com.github.MockBukkit:MockBukkit", version.ref = "minecraft-mockbukkit" }

# klibs
klibs-kdi = { module = "ru.astrainteractive.klibs:kdi", version.strictly = "1.3.1" }
klibs-kstorage = { module = "ru.astrainteractive.klibs:kstorage", version.strictly = "1.3.0" }
klibs-mikro = { module = "ru.astrainteractive.klibs:mikro-core", version.strictly = "1.4.0" }

# AstraLibs
minecraft-astralibs-ktxcore = { module = "ru.astrainteractive.astralibs:ktx-core", version.ref = "minecraft-astralibs" }
minecraft-astralibs-orm = { module = "ru.astrainteractive.astralibs:orm", version.ref = "minecraft-astralibs" }
minecraft-astralibs-spigot-core = { module = "ru.astrainteractive.astralibs:spigot-core", version.ref = "minecraft-astralibs" }
minecraft-astralibs-spigot-gui = { module = "ru.astrainteractive.astralibs:spigot-gui", version.ref = "minecraft-astralibs" }

# Fabric
minecraft-fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "minecraft-fabric-kotlin" }
minecraft-fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "minecraft-fabric-loader" }
minecraft-fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "minecraft-fabric-api" }
minecraft-mojang = { module = "com.mojang:minecraft", version.ref = "minecraft-version" }

[bundles]
exposed = ["exposed-java-time", "exposed-jdbc", "exposed-dao", "exposed-core"]
minecraft-bukkit = ["minecraft-paper-api", "minecraft-spigot-api", "minecraft-spigot-core", "minecraft-vaultapi", "minecraft-papi"]
testing-kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-coreJvm", "driver-jdbc", "driver-mysql", "kotlin-serialization", "kotlin-serializationJson"]
kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-coreJvm", "kotlin-serialization", "kotlin-serializationJson", "kotlin-serializationKaml", "kotlin-gradle"]

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }

# Minecraft
minecraft-fabric-loom = { id = "fabric-loom", version.ref = "minecraft-fabric-loom" }
minecraft-forge-net = { id = "net.minecraftforge.gradle", version.ref = "minecraft-forge-net" }

# Gradle
gradle-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradle-shadow" }
gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig" }

# klibs - core
klibs-gradle-detekt = { id = "ru.astrainteractive.gradleplugin.detekt", version.ref = "klibs-gradleplugin" }
klibs-gradle-detekt-compose = { id = "ru.astrainteractive.gradleplugin.detekt.compose", version.ref = "klibs-gradleplugin" }
klibs-gradle-dokka-root = { id = "ru.astrainteractive.gradleplugin.dokka.root", version.ref = "klibs-gradleplugin" }
klibs-gradle-dokka-module = { id = "ru.astrainteractive.gradleplugin.dokka.module", version.ref = "klibs-gradleplugin" }
klibs-gradle-java-core = { id = "ru.astrainteractive.gradleplugin.java.core", version.ref = "klibs-gradleplugin" }
klibs-gradle-stub-javadoc = { id = "ru.astrainteractive.gradleplugin.stub.javadoc", version.ref = "klibs-gradleplugin" }
klibs-gradle-publication = { id = "ru.astrainteractive.gradleplugin.publication", version.ref = "klibs-gradleplugin" }
klibs-gradle-rootinfo = { id = "ru.astrainteractive.gradleplugin.root.info", version.ref = "klibs-gradleplugin" }

# klibs - minecraft
klibs-gradle-minecraft-empty = { id = "ru.astrainteractive.gradleplugin.minecraft.empty", version.ref = "klibs-gradleplugin" }
klibs-gradle-minecraft-multiplatform = { id = "ru.astrainteractive.gradleplugin.minecraft.multiplatform", version.ref = "klibs-gradleplugin" }